### ISSUE TITLE
好吧，我发现问题了，我的mysql数据库会把大写字母变成小写

### ISSUE THREAD

**Issue by zachSen1206** [cckevincyh/LibrarySystem#11]
好吧，我发现问题了，我的mysql数据库会把大写字母变成小写

_Originally posted by @darkcavalier in https://github.com/cckevincyh/LibrarySystem/issues/1#issuecomment-369493265_

**Comment by zachSen1206** [comment]
老兄，我也碰到这个问题，是个初学者，需要怎么改呢，求指教

**Comment by cckevincyh** [comment]
> 老兄，我也碰到这个问题，是个初学者，需要怎么改呢，求指教

@zachSen1206 试试这个https://www.2cto.com/database/201309/246874.html
