### ISSUE TITLE
您好，有个问题

### ISSUE THREAD

**Issue by kongniijiwa** [cckevincyh/LibrarySystem#13]
这个系统同时借书的用户只能是3个么，我在借书页面超过三个人借书就提示借阅数量已达上限

**Comment by cckevincyh** [comment]
> 这个系统同时借书的用户只能是3个么，我在借书页面超过三个人借书就提示借阅数量已达上限

@nid88452 看的是系统内书的数量。

**Comment by kongniijiwa** [comment]
我设置了十几种书，每种二十本，借出去三本就提示上限。。。。

**Comment by cckevincyh** [comment]
> 这个系统同时借书的用户只能是3个么，我在借书页面超过三个人借书就提示借阅数量已达上限

项目太久了，有点不记得了，ReaderType 里面有个maxNum变量是控制最大可借书的数量。
