### ISSUE TITLE
给点测试数据SQL呗

### ISSUE THREAD

**Issue by Tulaoban** [cckevincyh/LibrarySystem#2]
我都部署成功了，但是我手动向数据加的admin数据，但是登录老找不到用户。也没看明白的你的密码校验是咋回事。亲可以给点测试数据SQL

**Comment by cckevincyh** [comment]
@Tulaoban 
INSERT INTO ADMIN (aid,username,name,pwd,state) VALUES(1,'admin','cairou','ISMvKXpXpadDiUoOSoAfww==','1');

INSERT INTO authorization VALUES('1','1','1','1','1','1','1','1','1');

**Comment by Tulaoban** [comment]
密码是啥？

**Comment by cckevincyh** [comment]
@Tulaoban  admin

**Comment by Tulaoban** [comment]
谢谢了。

**Comment by Tulaoban** [comment]
很尴尬。我的debugger看参数都传了。执行打印的sql也能查询到数据，很蒙、很明显有数据。但是就是返回的结果为null

**Comment by Tulaoban** [comment]
问下你jdk版本是多少？

**Comment by cckevincyh** [comment]
@Tulaoban 管理员的数据已经添加好了吗？不太清楚你说的返回null的情况是什么时候。

**Comment by Tulaoban** [comment]
178419096加个QQ我截图

**Comment by Tulaoban** [comment]
@cckevincyh 昨天那个问题解决了。和我的猜测一样。我今天换成jdk1.7就Ok了。谢谢你。
