### ISSUE TITLE
大神，不知道您是否有时间！

### ISSUE THREAD

**Issue by cmt077** [cckevincyh/LibrarySystem#3]
我是个初学者，在github上看到了您发布的项目！
部署时出了一些问题

**Comment by cmt077** [comment]
我借用的是这个LibrarySystem项目

**Comment by cmt077** [comment]
1049554300这是我QQ您有时间可否加一下

**Comment by cckevincyh** [comment]
@cmt077 你可以先去看看close掉的issues：
![image](https://user-images.githubusercontent.com/19624166/39682541-1234f266-51e3-11e8-81ca-4b47163d1ec4.png)
还是解决不了的话，再问问我。

**Comment by cmt077** [comment]
嗯，好，我试试！

**Comment by cckevincyh** [comment]
@cmt077 
web 应用都是部署到tomcat的webapps 目录下，而WebappClassLoader加载器加载WEB-INF/lib下的jar包。实际发布到tomcat时,仅仅只复制了WEB-INF/lib里面的jar包,所以出现eclipse可以正常编译但tomcat运行是找不到类。你可以看看你发布的tomcat的项目下的WEB-INF/lib下面的jar包是否已经部署好？
![image](https://user-images.githubusercontent.com/19624166/39687086-3a1d6620-51ff-11e8-81ab-97925cbbdbb7.png)，可以手动尝试加入jar包。
或者你可以试试改动下eclipse中WEB-INF/lib的形式，不用分文件夹放jar，可能结构不对无法直接复制WEB-INF/lib里面的jar包,直接使用：
![image](https://user-images.githubusercontent.com/19624166/39687126-6a5eccca-51ff-11e8-8b92-51c7fe8b9e2e.png)

**Comment by DuyinLoo88** [comment]
想问你一下，你这个导入读者时的密码默认是什么啊

**Comment by cckevincyh** [comment]
@DuyinLoo88 123456
