### ISSUE TITLE
图书管理系统运行问题

### ISSUE THREAD

**Issue by 929060568** [cckevincyh/LibrarySystem#6]
运行的时候出现了下图的错误
![1](https://user-images.githubusercontent.com/37527596/49013248-07626c00-f1b7-11e8-8bbb-d094ad1b7a91.png)
查询了一下，好像和这个文件有关系，自己mysql导入了文件的图书管理系统的数据库文件，账号密码也设置的自己的，不知道哪里出错了。
![2](https://user-images.githubusercontent.com/37527596/49013272-22cd7700-f1b7-11e8-9384-7916c570bc6b.png)

**Comment by cckevincyh** [comment]
> 运行的时候出现了下图的错误
> ![1](https://user-images.githubusercontent.com/37527596/49013248-07626c00-f1b7-11e8-8bbb-d094ad1b7a91.png)
> 查询了一下，好像和这个文件有关系，自己mysql导入了文件的图书管理系统的数据库文件，账号密码也设置的自己的，不知道哪里出错了。
> ![2](https://user-images.githubusercontent.com/37527596/49013272-22cd7700-f1b7-11e8-9384-7916c570bc6b.png)

这是另一个问题吗？我刚刚看到你的图片好像是classNotFound的问题，这个问题解决了？

**Comment by cckevincyh** [comment]
> > 运行的时候出现了下图的错误
> > ![1](https://user-images.githubusercontent.com/37527596/49013248-07626c00-f1b7-11e8-8bbb-d094ad1b7a91.png)
> > 查询了一下，好像和这个文件有关系，自己mysql导入了文件的图书管理系统的数据库文件，账号密码也设置的自己的，不知道哪里出错了。
> > ![2](https://user-images.githubusercontent.com/37527596/49013272-22cd7700-f1b7-11e8-9384-7916c570bc6b.png)
> 
> 这是另一个问题吗？我刚刚看到你的图片好像是classNotFound的问题，这个问题解决了？

你是不是改过了DB的URL，你那个URL貌似是错的，麻烦对比一下github上的看看是不是改错了。

**Comment by 929060568** [comment]
是的，我就一直改来改去的，现在是这个错误，错误内容是下图，cause by就是上图那个
![1](https://user-images.githubusercontent.com/37527596/49013693-958b2200-f1b8-11e8-9b8a-6bc94c483fa2.png)
还有就是，这个项目有个错误的符号，不知道哪里出错了
![2](https://user-images.githubusercontent.com/37527596/49013714-a76cc500-f1b8-11e8-9b75-0081600232f1.png)

**Comment by cckevincyh** [comment]
> 是的，我就一直改来改去的，现在是这个错误，错误内容是下图，cause by就是上图那个
> ![1](https://user-images.githubusercontent.com/37527596/49013693-958b2200-f1b8-11e8-9b8a-6bc94c483fa2.png)
> 还有就是，这个项目有个错误的符号，不知道哪里出错了
> ![2](https://user-images.githubusercontent.com/37527596/49013714-a76cc500-f1b8-11e8-9b75-0081600232f1.png)

参照一下这个：https://github.com/cckevincyh/OnLineTest/issues/4   
应该是jar包的路径有问题。

**Comment by cckevincyh** [comment]
> > 是的，我就一直改来改去的，现在是这个错误，错误内容是下图，cause by就是上图那个
> > ![1](https://user-images.githubusercontent.com/37527596/49013693-958b2200-f1b8-11e8-9b8a-6bc94c483fa2.png)
> > 还有就是，这个项目有个错误的符号，不知道哪里出错了
> > ![2](https://user-images.githubusercontent.com/37527596/49013714-a76cc500-f1b8-11e8-9b75-0081600232f1.png)
> 
> 参照一下这个：[cckevincyh/OnLineTest#4](https://github.com/cckevincyh/OnLineTest/issues/4)
> 应该是jar包的路径有问题。

截图看看你项目中java buid path里面的jar包情况。

**Comment by 929060568** [comment]
真的是打扰了，一直在麻烦你，你也一直在回复，改了改，jar包没问题了
![1](https://user-images.githubusercontent.com/37527596/49014399-f7e52200-f1ba-11e8-8cd6-a6bbf3462a77.png)
出现了以前的错误
![2](https://user-images.githubusercontent.com/37527596/49014407-fddb0300-f1ba-11e8-97fe-5db66d8cfe7c.png)
我也想问hibernate.cfg.xml是不是需要修改为我的数据库的路径、用户名和密码？（我已经修改）

**Comment by cckevincyh** [comment]
> 真的是打扰了，一直在麻烦你，你也一直在回复，改了改，jar包没问题了
> ![1](https://user-images.githubusercontent.com/37527596/49014399-f7e52200-f1ba-11e8-8cd6-a6bbf3462a77.png)
> 出现了以前的错误
> ![2](https://user-images.githubusercontent.com/37527596/49014407-fddb0300-f1ba-11e8-97fe-5db66d8cfe7c.png)
> 我也想问hibernate.cfg.xml是不是需要修改为我的数据库的路径、用户名和密码？（我已经修改）

看看你本地Tomact下面的项目中的lib内容截图。

**Comment by cckevincyh** [comment]
> > 真的是打扰了，一直在麻烦你，你也一直在回复，改了改，jar包没问题了
> > ![1](https://user-images.githubusercontent.com/37527596/49014399-f7e52200-f1ba-11e8-8cd6-a6bbf3462a77.png)
> > 出现了以前的错误
> > ![2](https://user-images.githubusercontent.com/37527596/49014407-fddb0300-f1ba-11e8-97fe-5db66d8cfe7c.png)
> > 我也想问hibernate.cfg.xml是不是需要修改为我的数据库的路径、用户名和密码？（我已经修改）
> 
> 看看你本地Tomact下面的项目中的lib内容截图。

数据库用户名和密码需要修改，URL应该不用，你导入sql脚本的是创建的应该是同个路径，除非你的端口号一开始设置的不是3306.

**Comment by 929060568** [comment]
这是截图，jar包都在
![3](https://user-images.githubusercontent.com/37527596/49014730-0bdd5380-f1bc-11e8-944a-e12ac9f349e8.png)
你说的url问题，我创建了一个新的数据库librarysystem，小写字母，导入了你的sql文件，我的是小写字母，所以改成了小写字母应该没问题吧，默认端口没改，所以应该没问题吧
![4](https://user-images.githubusercontent.com/37527596/49014840-5f4fa180-f1bc-11e8-8c8c-f74771f41e34.png)

**Comment by cckevincyh** [comment]
> 这是截图，jar包都在
> ![3](https://user-images.githubusercontent.com/37527596/49014730-0bdd5380-f1bc-11e8-944a-e12ac9f349e8.png)
> 你说的url问题，我创建了一个新的数据库librarysystem，小写字母，导入了你的sql文件，我的是小写字母，所以改成了小写字母应该没问题吧，默认端口没改，所以应该没问题吧
> ![4](https://user-images.githubusercontent.com/37527596/49014840-5f4fa180-f1bc-11e8-8c8c-f74771f41e34.png)

只要run起来报的不是db的问题应该没问题。

**Comment by cckevincyh** [comment]
> > 这是截图，jar包都在
> > ![3](https://user-images.githubusercontent.com/37527596/49014730-0bdd5380-f1bc-11e8-944a-e12ac9f349e8.png)
> > 你说的url问题，我创建了一个新的数据库librarysystem，小写字母，导入了你的sql文件，我的是小写字母，所以改成了小写字母应该没问题吧，默认端口没改，所以应该没问题吧
> > ![4](https://user-images.githubusercontent.com/37527596/49014840-5f4fa180-f1bc-11e8-8c8c-f74771f41e34.png)
> 
> 只要run起来报的不是db的问题应该没问题。

不过之前也有和你之前报同样错误的人，你可以参考下，我也不确定URL改了会不会有问题。https://github.com/cckevincyh/LibrarySystem/issues/1#issuecomment-368866078

**Comment by cckevincyh** [comment]
> > > 这是截图，jar包都在
> > > ![3](https://user-images.githubusercontent.com/37527596/49014730-0bdd5380-f1bc-11e8-944a-e12ac9f349e8.png)
> > > 你说的url问题，我创建了一个新的数据库librarysystem，小写字母，导入了你的sql文件，我的是小写字母，所以改成了小写字母应该没问题吧，默认端口没改，所以应该没问题吧
> > > ![4](https://user-images.githubusercontent.com/37527596/49014840-5f4fa180-f1bc-11e8-8c8c-f74771f41e34.png)
> > 
> > 
> > 只要run起来报的不是db的问题应该没问题。
> 
> 不过之前也有和你之前报同样错误的人，你可以参考下，我也不确定URL改了会不会有问题。[#1 (comment)](https://github.com/cckevincyh/LibrarySystem/issues/1#issuecomment-368866078)

最终的exception报的就是hibernate的那个问题吗？所以可能归根结底有可能是你配置的URL大小写的问题。

**Comment by 929060568** [comment]
现在问题是下面的那个，我查了查，网上的方法都是导入什么maven项目的有关内容，我也不知道该怎么改
![6](https://user-images.githubusercontent.com/37527596/49015293-9bcfcd00-f1bd-11e8-828c-17db2171520a.png)

**Comment by cckevincyh** [comment]
> 现在问题是下面的那个，我查了查，网上的方法都是导入什么maven项目的有关内容，我也不知道该怎么改
> ![6](https://user-images.githubusercontent.com/37527596/49015293-9bcfcd00-f1bd-11e8-828c-17db2171520a.png)

这是全部的exception了吗？下面还有吗？

**Comment by 929060568** [comment]
这是完整的了
![7](https://user-images.githubusercontent.com/37527596/49015847-409eda00-f1bf-11e8-8c69-d157d42d1758.png)

**Comment by cckevincyh** [comment]
> 这是完整的了
> ![7](https://user-images.githubusercontent.com/37527596/49015847-409eda00-f1bf-11e8-8c69-d157d42d1758.png)

你对着看你eclipse上面的java build path的路径和你tomcat本地的路径就知道为什么会找不到jar包了。可能我的myeclipse跟你不同，我deploy的时候会把在文件夹里面的jar拷贝到外层目录。你仔细看看你java build path的路径都是在WEB-INF/lib下面这一层，但是你本地tomcat的jar包都是在文件夹里面的。

**Comment by cckevincyh** [comment]
> > 这是完整的了
> > ![7](https://user-images.githubusercontent.com/37527596/49015847-409eda00-f1bf-11e8-8c69-d157d42d1758.png)
> 
> 你对着看你eclipse上面的java build path的路径和你tomcat本地的路径就知道为什么会找不到jar包了。可能我的myeclipse跟你不同，我deploy的时候会把在文件夹里面的jar拷贝到外层目录。你仔细看看你java build path的路径都是在WEB-INF/lib下面这一层，但是你本地tomcat的jar包都是在文件夹里面的。

所以你现在有两个solution，一个是把eclipse上面lib下面文件夹里面的jar包都拉到lib这一层目录下，然后重新deploy，或者到tomcat的目录下，手动把jar包都拷贝到外层来，我deploy的时候这个工作就已经完成了，所以我的tomcat下面的lib目录是这样的：
![image](https://user-images.githubusercontent.com/19624166/49017017-b48eb180-f1c2-11e8-87bc-b87e902bf4a9.png)

**Comment by 929060568** [comment]
你好，按照你的方法，之前的问题解决了，可是又回到了原来的问题里面
![8](https://user-images.githubusercontent.com/37527596/49019497-06d2d100-f1c9-11e8-82b2-d2c125e2f800.png)
用户名和密码正确，数据库的名字也确实为librarysystem
![9](https://user-images.githubusercontent.com/37527596/49019531-18b47400-f1c9-11e8-8cdf-e494639d2576.png)
![10](https://user-images.githubusercontent.com/37527596/49019534-1a7e3780-f1c9-11e8-87a4-df4ceaa2e35c.png)
有点无奈QAQ

**Comment by cckevincyh** [comment]
> 你好，按照你的方法，之前的问题解决了，可是又回到了原来的问题里面
> ![8](https://user-images.githubusercontent.com/37527596/49019497-06d2d100-f1c9-11e8-82b2-d2c125e2f800.png)
> 用户名和密码正确，数据库的名字也确实为librarysystem
> ![9](https://user-images.githubusercontent.com/37527596/49019531-18b47400-f1c9-11e8-8cdf-e494639d2576.png)
> ![10](https://user-images.githubusercontent.com/37527596/49019534-1a7e3780-f1c9-11e8-87a4-df4ceaa2e35c.png)
> 有点无奈QAQ

你试试把db的数据删掉，重新导入我的SQL脚本，URL也不要改，换成原来大写开头的。我怀疑就是大小写的问题。

**Comment by 929060568** [comment]
db的数据删掉了，运行了你给的脚本，URL换成了你原来的那个，不行啊QAQ，不知道哪里出错了
![1](https://user-images.githubusercontent.com/37527596/49020574-bf9a0f80-f1cb-11e8-9a32-260fef30d464.png)
或许是我的系统或者IDE问题吗？我找时间在ubuntu上运行一下试试，感谢前辈抽出这么多时间帮我解答问题QAQ，问一下前辈现在是工作了或者还在读书啊

**Comment by cckevincyh** [comment]
> db的数据删掉了，运行了你给的脚本，URL换成了你原来的那个，不行啊QAQ，不知道哪里出错了
> ![1](https://user-images.githubusercontent.com/37527596/49020574-bf9a0f80-f1cb-11e8-9a32-260fef30d464.png)
> 或许是我的系统或者IDE问题吗？我找时间在ubuntu上运行一下试试，感谢前辈抽出这么多时间帮我解答问题QAQ，问一下前辈现在是工作了或者还在读书啊

你改完之后有重新编译deploy吗？你看看tomcat项目里面的配置改变没有，如果还不行，再试试把URL改回小写的试试看。

**Comment by cckevincyh** [comment]
> > db的数据删掉了，运行了你给的脚本，URL换成了你原来的那个，不行啊QAQ，不知道哪里出错了
> > ![1](https://user-images.githubusercontent.com/37527596/49020574-bf9a0f80-f1cb-11e8-9a32-260fef30d464.png)
> > 或许是我的系统或者IDE问题吗？我找时间在ubuntu上运行一下试试，感谢前辈抽出这么多时间帮我解答问题QAQ，问一下前辈现在是工作了或者还在读书啊
> 
> 你改完之后有重新编译deploy吗？你看看tomcat项目里面的配置改变没有，如果还不行，再试试把URL改回小写的试试看。

2018刚毕业的，在工作了。
