### ISSUE TITLE
小白刚刚开始学习Java Web，看见前辈的系统功能很强大，想研究一下，一上来就碰见了问题，期待前辈给予帮助，谢谢

### ISSUE THREAD

**Issue by Liujingrui** [cckevincyh/LibrarySystem#9]
前辈，能否给指导下
![360截图20190323095503001](https://user-images.githubusercontent.com/20753284/54860221-136bce00-4d52-11e9-9d34-98ca4afc3f06.jpg)

Tomcat是没有问题的
![360截图20190323095600961](https://user-images.githubusercontent.com/20753284/54860241-41e9a900-4d52-11e9-891f-7d064d0a5228.jpg)

Eclipse下结构是这样的，应该也没问题吧
![image](https://user-images.githubusercontent.com/20753284/54860267-a0af2280-4d52-11e9-878f-83314d3109dc.png)

试了试网上的解决方案，都没效果。
![image](https://user-images.githubusercontent.com/20753284/54860276-bc1a2d80-4d52-11e9-9f43-797c62a617ff.png)

期待前辈的帮助，该怎样部署一下系统，谢谢。

**Comment by cckevincyh** [comment]
> 前辈，能否给指导下
> ![360截图20190323095503001](https://user-images.githubusercontent.com/20753284/54860221-136bce00-4d52-11e9-9d34-98ca4afc3f06.jpg)
> 
> Tomcat是没有问题的
> ![360截图20190323095600961](https://user-images.githubusercontent.com/20753284/54860241-41e9a900-4d52-11e9-891f-7d064d0a5228.jpg)
> 
> Eclipse下结构是这样的，应该也没问题吧
> ![image](https://user-images.githubusercontent.com/20753284/54860267-a0af2280-4d52-11e9-878f-83314d3109dc.png)
> 
> 试了试网上的解决方案，都没效果。
> ![image](https://user-images.githubusercontent.com/20753284/54860276-bc1a2d80-4d52-11e9-9f43-797c62a617ff.png)
> 
> 期待前辈的帮助，该怎样部署一下系统，谢谢。

@Liujingrui 看看你部署到tomcat之后，tomcat目录里面有没有这个项目存在，位置是不是正确的。
